"""Add Research Workshop tables for opportunities and trends

Revision ID: 6ab646c0b425
Revises: 2c2c208bb900
Create Date: 2025-07-13 23:02:21.084592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab646c0b425'
down_revision: Union[str, Sequence[str], None] = '2c2c208bb900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Research Workshop tables
    
    # Trend snapshots table
    op.create_table(
        'trend_snapshots',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('source', sa.String(100), nullable=False),
        sa.Column('keywords', sa.ARRAY(sa.Text()), nullable=False),
        sa.Column('metrics', sa.JSON(), nullable=False),
        sa.Column('geographic_data', sa.JSON(), nullable=True),
        sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('processed', sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Research metrics table
    op.create_table(
        'research_metrics',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
        sa.Column('agent_name', sa.String(100), nullable=False),
        sa.Column('execution_date', sa.Date(), nullable=False),
        sa.Column('opportunities_found', sa.Integer(), server_default='0', nullable=False),
        sa.Column('opportunities_approved', sa.Integer(), server_default='0', nullable=False),
        sa.Column('success_rate', sa.Numeric(3, 2), nullable=True),
        sa.Column('average_score', sa.Numeric(3, 2), nullable=True),
        sa.Column('metrics_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Update market_opportunities table with additional fields
    # Note: trend_data already exists, so we skip it
    op.add_column('market_opportunities', sa.Column('market_analysis', sa.JSON(), nullable=True))
    op.add_column('market_opportunities', sa.Column('sourcing_options', sa.JSON(), nullable=True))
    op.add_column('market_opportunities', sa.Column('score', sa.Numeric(3, 2), nullable=True))
    op.add_column('market_opportunities', sa.Column('discovery_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('market_opportunities', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('market_opportunities', sa.Column('reviewer_id', sa.UUID(), nullable=True))
    op.add_column('market_opportunities', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('market_opportunities', sa.Column('status', sa.String(50), server_default='pending', nullable=False))
    
    # Create indexes for performance
    op.create_index('idx_opportunities_status', 'market_opportunities', ['status'])
    op.create_index('idx_opportunities_score', 'market_opportunities', ['score'], postgresql_using='btree', postgresql_ops={'score': 'DESC'})
    op.create_index('idx_trends_processed', 'trend_snapshots', ['processed'])
    op.create_index('idx_trends_captured', 'trend_snapshots', ['captured_at'], postgresql_using='btree', postgresql_ops={'captured_at': 'DESC'})
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('idx_trends_captured', table_name='trend_snapshots')
    op.drop_index('idx_trends_processed', table_name='trend_snapshots')
    op.drop_index('idx_opportunities_score', table_name='market_opportunities')
    op.drop_index('idx_opportunities_status', table_name='market_opportunities')
    
    # Drop columns from market_opportunities
    op.drop_column('market_opportunities', 'status')
    op.drop_column('market_opportunities', 'review_notes')
    op.drop_column('market_opportunities', 'reviewer_id')
    op.drop_column('market_opportunities', 'reviewed_at')
    op.drop_column('market_opportunities', 'discovery_date')
    op.drop_column('market_opportunities', 'score')
    op.drop_column('market_opportunities', 'sourcing_options')
    op.drop_column('market_opportunities', 'market_analysis')
    
    # Drop tables
    op.drop_table('research_metrics')
    op.drop_table('trend_snapshots')
    
    # ### end Alembic commands ###
